title:              공부하는 개발자
email:              csooy38@example.com
description:        공부하는 개발자, 최수연의 블로그
author:             csooy38
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "http://www.csooy38.com/"

# Social Profiles
twitter_username:  
github_username:    csooy38
facebook_username: 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
